# Copyright Max R. P. Grossmann, Holger Gerhardt, et al., 2025.
# SPDX-License-Identifier: LGPL-3.0-or-later

"""Admin module - re-exports from focused service modules."""

# Re-export from auth service
from uproot.services.auth import (
    ADMINS,
    ADMINS_HASH,
    ADMINS_SECRET_KEY,
    cleanup_expired_tokens,
    create_auth_token,
    create_auth_token_async,
    create_auth_token_for_user,
    create_token_internal,
    ensure_globals,
    from_cookie,
    get_active_auth_sessions,
    get_active_tokens,
    get_secret_key,
    get_serializer,
    make_pow_challenge,
    require_bearer_token,
    revoke_all_user_tokens,
    revoke_auth_token,
    store_active_tokens,
    verify_auth_token,
    verify_bearer_token,
    verify_pow,
)

# Re-export from config service
from uproot.services.config_service import (
    announcements,
    config_summary,
    configs,
    displaystr,
    praise,
)

# Re-export from data service
from uproot.services.data_service import (
    DisplayValue,
    data_display,
    everything_from_session,
    everything_from_session_display,
    generate_briefcase,
    generate_custom_csv,
    generate_custom_jsonl,
    generate_data,
    generate_jsonl,
    is_custom_data_export,
    pipeline_result_display,
)

# Re-export from player service
from uproot.services.player_service import (
    adjust_timeout,
    adminchat_overview,
    adminchat_thread,
    adminmessage,
    advance_by_one,
    fields_from_all,
    group_players,
    info_online,
    insert_fields,
    mark_dropout,
    put_to_end,
    redirect,
    reload,
    revert_by_one,
    run_new_player,
    send_adminchat,
    send_adminchat_to_players,
    set_adminchat_replies,
    set_adminchat_replies_for_players,
)

# Re-export from room service
from uproot.services.room_service import (
    close_room,
    delete_room,
    disassociate,
    ensure_session_available_for_room,
    room_exists,
    rooms,
    set_room_capacity,
    set_room_open,
)

# Re-export from session service
from uproot.services.session_service import (
    PipelineInvocationError,
    flip_active,
    flip_testing,
    get_digest,
    get_pipelines,
    pipeline_call_kwargs,
    run_new_session,
    run_pipeline,
    session_exists,
    sessions,
    update_description,
    update_settings,
)

__all__ = [
    # Auth
    "ADMINS",
    "ADMINS_HASH",
    "ADMINS_SECRET_KEY",
    # Data
    "DisplayValue",
    # Session
    "PipelineInvocationError",
    # Player
    "adjust_timeout",
    "adminchat_overview",
    "adminchat_thread",
    "adminmessage",
    "advance_by_one",
    # Config
    "announcements",
    "cleanup_expired_tokens",
    # Room
    "close_room",
    "config_summary",
    "configs",
    "create_auth_token",
    "create_auth_token_async",
    "create_auth_token_for_user",
    "create_token_internal",
    "data_display",
    "delete_room",
    "disassociate",
    "displaystr",
    "ensure_globals",
    "ensure_session_available_for_room",
    "everything_from_session",
    "everything_from_session_display",
    "fields_from_all",
    "flip_active",
    "flip_testing",
    "from_cookie",
    "generate_briefcase",
    "generate_custom_csv",
    "generate_custom_jsonl",
    "generate_data",
    "generate_jsonl",
    "get_active_auth_sessions",
    "get_active_tokens",
    "get_digest",
    "get_pipelines",
    "get_secret_key",
    "get_serializer",
    "group_players",
    "info_online",
    "insert_fields",
    "is_custom_data_export",
    "make_pow_challenge",
    "mark_dropout",
    "pipeline_call_kwargs",
    "pipeline_result_display",
    "praise",
    "put_to_end",
    "redirect",
    "reload",
    "require_bearer_token",
    "revert_by_one",
    "revoke_all_user_tokens",
    "revoke_auth_token",
    "room_exists",
    "rooms",
    "run_new_player",
    "run_new_session",
    "run_pipeline",
    "send_adminchat",
    "send_adminchat_to_players",
    "session_exists",
    "sessions",
    "set_adminchat_replies",
    "set_adminchat_replies_for_players",
    "set_room_capacity",
    "set_room_open",
    "store_active_tokens",
    "update_description",
    "update_settings",
    "verify_auth_token",
    "verify_bearer_token",
    "verify_pow",
]
